### ISSUE TITLE
How to get client class

### ISSUE THREAD

**Issue by TakeFy** [Ayfri/Advanced-Command-Handler#54] opened 2021-01-13 11:33 UTC
Hey i'm using the command handler for 6 month now it's awesome working perfect on 500 guilds + ! But how can I get client information in the file that i iniated the command handler (index.js) in previous version it was CommandHandler.client but know it's returning _undefined_ so how can I do ?
here is an image.

![image](https://user-images.githubusercontent.com/62612084/104447103-9dc29900-559b-11eb-8d2a-dbe260bdfa04.png)

Thanks for helping me, I'm giving lot's of support.
When i log CommandHandler it's returning me this 

![image](https://user-images.githubusercontent.com/62612084/104447493-29d4c080-559c-11eb-9df9-bfd507220ab5.png)
and i want to get the thing in red 

what I did : 

console.log(CommandHandler.client) returning undefined

**Comment by Ayfri** [comment] 2021-01-13 11:38
Duplicate of #53, just a fail I suppose ^^

**Closed by Ayfri** 2021-01-13 11:38 UTC

**Comment by TakeFy** [comment] 2021-01-13 11:44
yeah it was saying 404 error
